language: groovy
jdk:
- oraclejdk7
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"  
  - secure: BcvI6uMqd0kcjMknkcDYunESyYC3LWvO/QDgEXCv4HNCiZ/NO/9em4qNcB1F0pR2cGjIdyPMZS3MkFsHDNEU8VqmEIMSwoMys5cfu70wAIIk7hsvHJyc7SbGEHj7Mn+Z++guKCcLjjv+mZmB3R/2mMIHm41QlLIln75mLrbrwIg=
  - secure: GscDMD/9TgJeP67CS89Hj486m33Dsrt+Uwk8ruylTwdUtmPnOWz04NegejKa64jJaLQm2w/FbqXQLL1V9Cp4MDeeo6GLG6PrecXiCmJ6AYnSFB3rXYSLru1mrXPqgz9F9yXA7dhVurnEdnb7RsiPYtKo32v4IBLCRzIA93wmcBk=
  - secure: kBeaNzEuThDWeynwh4kVvdjRu9KffayX6BEsBJCH1VTnLG2/8MBylM22fUD81cz/wDATgbHBony1tD//guiJkNNZo98SEVP5ucvlwiBucE1+wMYlcE7b099KPvdKj78HhRwCfSeurJO6BKxgD4LEyr4dU7mYPHqBupZHsCSekJo=
